language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=examples/Init/Init.ino
install:
    # Install PlatformIO
    - pip install -U platformio
    # Install MsTimer2 library
    - platformio lib install 137
script:
    - platformio ci --lib="." --board=uno --board=leonardo --board=diecimilaatmega168 --board=megaatmega2560 --board=megaatmega1280
